#日志配置
logging:
  pattern:
    level: DEBUG
#数据源配置 (配置多数据源)
spring:
  datasource:
    primary: #主数据源
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql:///study
      username: root
      password: root
    secondary: #次数据源
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql:///test
      username: root
      password: root


       

