##全局配置文件

##日志文件
logging:
  pattern:
    level: DEBUG

##redis属性

spring:
  redis:
    host: 127.0.0.1    ##主机地址
    port: 6379         ##主机端口
    database: 0        ##Redis数据库索引,默认为0
    password:          ##默认为空
    timeout: 0         ##连接超时时间（毫秒）
    pool:
      max-active: 8    ##连接池最大连接数量（使用负值标识无限制）
      max-wait: -1     ##最大连接时间
      max-idle: 8      ##最大空闲连接
      min-idle: 0      ##最小空闲连接
      